language: rust
rust: [nightly]
cache: cargo
env:
  global:
    - RUSTFLAGS="-Z external-macro-backtrace"
  matrix:
    - RELEASE_FLAG=""
    - RELEASE_FLAG="--release"

install:
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d ' ' -f 1)"

script:
  - cargo check --verbose --all $RELEASE_FLAG
  - cargo test --verbose --all $RELEASE_FLAG
  - cargo doc --verbose --all $RELEASE_FLAG
  - cargo fmt --all -- --check
